### ISSUE TITLE
Downloaded CSV file has no extension

### ISSUE THREAD

**Issue by maumrsms** [wazuh/wazuh-splunk#1049] opened 2021-04-07 00:00 UTC
| Wazuh | Splunk |
| ----- | ------- |
| 4.1.4   | 8.1.2     |

**Description**
Downloaded CSV file from **Management → Groups** has no extension, thus, cannot be easily opened until it is modified.

**Steps to reproduce**

1. Go to Management → Groups
2. See any group details
3. Click on 'Formatted'
4. Downloaded file has no extension

**Screenshots**
For this group:
![ae366019604344618a98b013c7b49ede](https://user-images.githubusercontent.com/29696136/113791759-b665c980-971a-11eb-8378-e1d72a44f12a.png)
I downloaded this `download (1)` file:
![d75060ef42ae4a839b478c1eb885821f](https://user-images.githubusercontent.com/29696136/113791852-ef05a300-971a-11eb-861a-38394bb78edf.png)

**Additional context**
Tested this in Microsoft Edge

**Comment by asteriscos** [comment] 2021-04-14 15:22
Hi!

I tried to run into this issue, but I wasn't able to reproduce it.
I tested it on Edge, Firefox and Chrome with no avail. If you have any extra information or steps it may help.

Thanks!

![image](https://user-images.githubusercontent.com/9343732/114735226-5aeb9b00-9d1b-11eb-8c07-413664874dfe.png)

**Comment by maumrsms** [comment] 2021-04-14 16:40
Hi!
I was performing the tests stated here: https://docs.google.com/spreadsheets/d/1OMkTqmjQ5TZ7wXjMraBJ-FaI-jUPk1swh3DZ4ilN9nc/edit#gid=233428767
Specifically the "Management - Groups" section when this issue happened. The steps performed were:

Go to: **Management - Groups** and from there:
1. List groups.
2. Search groups.
3. Create groups.
4. Remove a group.
5. Add one agent to a group.
6. Add more than one agent to a group.
7. Remove an agent from a group.
8. Remove more than one agent from a group.
9. Edit group configuration.
10. Export group details in PDF using granular options.
11. Export group details in PDF with no granular options.
12. Formatted should export the output for the different tables.

**Comment by asteriscos** [comment] 2021-04-16 14:46
Hi!
I realised I wasn't able to reproduce the issue because a PR fixing this issue was already merged. I just linked it.

**Closed** 2021-04-19 14:26 UTC
Labels: bug, operations
