### ISSUE TITLE
API Credentials Not Getting Stored in Splunk App

### ISSUE THREAD

**Issue by suryjuto** [wazuh/wazuh-splunk#98] opened 2018-06-02 13:16 UTC
Upgraded to v3.2.4 r6 this morning on Splunk SH.  When saving the previously working credentials it returns "Cannot add API without connection".  Validated API is listening on port, SSL configured correctly and logged into API via web browser.

**Comment by manuasir** [comment] 2018-06-02 13:21
Hi @suryjuto ,
An upcoming hotfix is being worked, I'll let you know when it's ready.Apologies for the inconvenience.

Best regards

**Comment by suryjuto** [comment] 2018-06-02 13:40
No worries, Manu.

Looks like the deb package is still causing issues for the wazuh-api
installer so I'm kind of dead in the water right now anyways.

**Comment by manuasir** [comment] 2018-06-02 18:54
Hi @suryjuto ,

Please, in order to update to the last version follow these steps:

1. Uninstall the current version of the app:
```
# /opt/splunk/bin/splunk remove app SplunkAppForWazuh
```
2. Download the new version from our [repository](https://github.com/wazuh/wazuh-splunk/releases/download/v3.2.4-7.1.1/v3.2.4_7.1.1.tar.gz).
3. Install the app on Splunk:
```
# /opt/splunk/bin/splunk install app v3.2.4_7.1.1.tar.gz
```
4. Restart splunk service:
```
# /opt/splunk/bin/splunk restart
```
5. Open the Wazuh app in your browser and navigate to Settings button if you're not redirected, and press 'Remove all' button in order to empty the current database and avoid possible inconsistencies. Then add your APIs.
Please,don't hesitate to open a new issue if needed and thank you for your report.

Best regards

**Comment by manuasir** [comment] 2018-06-03 11:20
Hi @suryjuto ,

Could you add screenshots of the issue you're facing? Please, open up the browser console by pressing F12 and make screenshots of any red message you may find, also add any relevant information you might consider to be useful for this issue.
 Also, what browser are you using? We know this version is facing troubles in Firefox ([we are already working on that issue](https://github.com/wazuh/wazuh-splunk/issues/94)).
Even if there are no inserted APIs, I'd recommend you to press 'Remove all' due to inconsistences that might have in KVstore.

Thanks for your patience,
Regards

**Comment by suryjuto** [comment] 2018-06-03 11:31
Followed your steps and clicked 'Remove All' first.

Opened JavaScript console and captured the attached screenshot.

Browser is Chrome.

[image: image.png]

**Comment by manuasir** [comment] 2018-06-03 11:36
Sorry @suryjuto , the image wasn't uploaded. You can upload it to github by dragging it and dropping into the text box.

Regards

**Comment by suryjuto** [comment] 2018-06-03 11:48
Try this:

![image](https://user-images.githubusercontent.com/24494768/40886260-8ba12c6c-6702-11e8-9004-558bfd49230f.png)

**Comment by manuasir** [comment] 2018-06-03 12:37
Hi @suryjuto , 

I will research about your problem and let you know about any solution. 
Thanks for your patience.

Regards

**Comment by manuasir** [comment] 2018-06-12 09:52
Hi @suryjuto,

After trying to reproduce your case I think this issue was related to timeouts in backend side.
We just released Wazuh v3.3.0, this version includes API fixes and several improvements so I'd recommend to you to upgrade to it by following the [official Wazuh documentation](https://documentation.wazuh.com/current/installation-guide/upgrading/index.html) and also to install the last release v3.3.0-7.1.1 of this app. It resolves fixes among which is this one. 
You can get the last release from [here](https://github.com/wazuh/wazuh-splunk/releases/download/v3.3.0-7.1.1/v3.3.0_7.1.1.tar.gz).
I'm awaiting your feedback, thanks very much for your patience.

Best regards

**Comment by manuasir** [comment] 2018-07-10 10:32
Hi @suryjuto, 

I'm going to close this issue since it's been a month since it was opened and fixed. 
Please, don't hesitate to open a new one in the future. I'll be glad to help you with anything you may need.

Best regards

**Closed by manuasir** 2018-07-10 10:32 UTC
Labels: 3.3, backend, bug

**Comment by suryjuto** [comment] 2018-07-10 13:20
Thanks Manu.  We moved and servers are in storage and I can’t test yet.


________________________________
